name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify your Python version

    -    - name: Install dependencies
        run: |
          source .venv/Scripts/activate
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          source .venv/Scripts/activate
          pytest
    - name: Build and deploy
      run: backend/app.py
